prev <- function(mod, ...) UseMethod("prev")
fnPregPrev <- function(mod, fp, ...) UseMethod("fnPregPrev")
incid <- function(mod, ...) UseMethod("incid")
simmod <- function(fp, ...) UseMethod("simmod")
simfit <- function(fit, ...) UseMethod("simfit")
