#!/bin/bash

# The parent commit to use for the new branch.
# this is the very first commit and contains only an empty BODY.md
BRANCH_PARENT='f4f94496d32572ff9ee3dede15f16571c9edb765'

# TODO: validate the name choice
git checkout -b "private-${1}" ${BRANCH_PARENT}
